name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'test'  # This should match the job name in unit_tests.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Auto-merge Dependabot PRs
        if: ${{ success() }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}